# Generated by Django 3.0.4 on 2020-10-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0003_auto_20200330_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='float_lat',
            field=models.FloatField(blank=True, default=12.12, null=True, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='float_lon',
            field=models.FloatField(blank=True, default=12.12, null=True, verbose_name='Lon'),
        ),
        migrations.AlterField(
            model_name='event',
            name='str_location',
            field=models.CharField(blank=True, default='test<br><br', max_length=250, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='str_timezone',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Timezone'),
        ),
    ]
